### ISSUE TITLE
Update `api-server` template to use the new declarative middleware registration

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-workspace#167]
https://github.com/strongloop/loopback/issues/739 and https://github.com/strongloop/loopback-boot/issues/44 implement a declarative solution for registering components via `middleware.json`.

We should update the `api-server` template to use this new mechanism.

**Tasks**
- [x] #169 - Modify the template
- [x] https://github.com/strongloop/generator-loopback/pull/73 Fix `yo loopback:example` to work with the new template
- [x] strongloop/loopback-boot#74 configure paths relative to `middleware.json` file, e.g. for `serve-static`.
- [x] https://github.com/strongloop/loopback-workspace/pull/171 Remove static middleware example from `server/server.js`
- [x] Update the documentation (see https://gist.github.com/bajtos/e7eaba736ff096916b71 and https://github.com/strongloop/loopback/issues/863)
- [x] Write a migration guide describing how to upgrade existing apps to use the new style of middleware registration - added to the docs draft - see https://gist.github.com/bajtos/e7eaba736ff096916b71#file-2-upgrade-guide-md

**Out of scope**
- https://github.com/strongloop/loopback-boot/issues/75 Declaratively load loopback.rest and loopback-explorer
