### ISSUE TITLE
Support async boot scripts OOTB

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-workspace#170]
We need to rework `server/server.js` template to support async boot scripts.

```
boot(app, __dirname, function(err) {
  if (err) throw err;
  // start the server if `$ node server.js`
  if (require.main === module) {
    app.start();
  });
```

In order to support the scenario when the app is loaded via `require` but not started, e.g. in loopback-sdk-angular-cli, we need to modify loopback-boot to emit an event when the boot process is finished, e.g. `app.emit('ready')`.

**Tasks**

 - [x] https://github.com/strongloop/loopback-boot/pull/77 modify loopback-boot to emit `ready` event (or similar)
 - [x] https://github.com/strongloop/loopback-workspace/pull/172 rework `server/server.js` template to defer `app.start` until `boot(app)` is finished
 - [x] https://github.com/strongloop/generator-loopback/pull/74 fix `slc loopback:example` to use async boot script for generating models, see [example/templates/server/boot/create-sample-data.js](https://github.com/strongloop/generator-loopback/blob/master/example/templates/server/boot/create-sample-data.js)

**Comment by chandadharap** [comment]
@bajtos The three tasks look check-marked as done?

**Comment by bajtos** [comment]
> @chandadharap The three tasks look check-marked as done?

@superkhau ticked them off before his pull requests were landed. I removed the check-marks and added links to the relevant pull requests.

**Comment by superkhau** [comment]
Close.

**Comment by superkhau** [comment]
Done.
