### ISSUE TITLE
Miroslav's TODO for yeoman

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-workspace#53]
List of changes required by `yo loopback`:
#62
- [x] Remove `id` from the generated ACL entries in `models.json`
#71
- [x] Simplify `app.started`, drop `started` event in favour of `listening` (see strongloop/loopback#357).
#69
- [x] Provide a hook allowing workspace API consumers to supply custom `ncp` implementation, e.g. yeoman's `directory` function.
#61
- [x] ensure js files are generated (`rest/rest.js`, `server/server.js`)
#63
- [x] Depending on the component type, some configuration files are optional. E.g. the empty root component does not need any `*.json` files.
- [x] Remove workspace metadata from generated JSON files, e.g. `componentName` and `configFile` in `rest/datasources.json`, `componentName` in `server/models.json`.
- [x] `package.json` generated by the current template sets `name` to `.` instead of the project name.
- [x] implement `Workspace.isValidDir` (see `Project.isValidProjectDir` in 2.x)
- [x] Fix boot: include `loopback-boot 2.x` in package.json, drop `email` datasource, use capital model names in `rest/models.json` (`User` instead of `user`).
- [x] API: make `componentName` required in all entities
- [x] Refactor the `server` template to use the boot-based registration of middleware (see example-full-stack).
#56
- [x] Modify value provides in `models/model-access-control.js`, use `{name, value}` instead of `{value, humanized}`.
